on:
  push:
  pull_request:
    paths-ignore:
      - '**.md'

name: Continuous integration

jobs:
  macos-build-universal-macos-latest:
    name: macOS (Universal) @ macos-latest
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Install dependencies
        run: brew install
          nasm
      - name: Configure
        run: cmake -B build -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"
      - name: Build
        run: cmake --build build -j "$(sysctl -n hw.logicalcpu)"
