on:
  push:
  pull_request:
    paths-ignore:
      - '**.md'

name: Continuous integration

jobs:
  ubuntu-build:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y
          libasound2-dev
          libgl-dev
          libglu1-mesa-dev
          libgtk-3-dev
          libjack-dev
          libmad0-dev
          libpulse-dev
          libudev-dev
          libusb-dev
          libxinerama-dev
          libx11-dev
          libxrandr-dev
          libxtst-dev
          nasm
      - name: Configure
        run: cmake -B build -DWITH_FFMPEG_JOBS="$(nproc)"
      - name: Build
        run: cmake --build build --parallel "$(nproc)"
      - name: List runtime libraries
        run: ldd ./itgmania
      - name: remove libglu
        run: sudo apt-get remove -y libglu1-mesa-dev libglu1-mesa
      - name: List runtime libraries again
        run: ldd ./itgmania
      - name: Try to run
        run: ./itgmania
